#!/bin/dash

# Change $SHELI_DIR with the actual directory the lib is in
export SHELI_DIR="/opt/sheli"
. "${SHELI_DIR}/sheli.sh"

argparse__add_argument name='pikachu' flags='-p,--pika' nargs='?' const='thunder'

demo__args() {
  if [ "${#}" -eq 0 ]; then
    printf 'You did not provide any argument\n'
  else
    printf 'These are the arguments you used:\n'
    for arg; do
      echo "${arg}"
    done
  fi
}

demo__prints() {
  if "${BACKGROUND}"; then
    printf 'Running in background, printing nothing!\n' >&2
  else
    DEBUG=true print_debug 'Example of a debug message'
    print_good 'Example of a good message'
    print_bad 'Example of a bad message'
    print_error 'Example of error'
    print_warning 'Example of warning'
    print_info 'Example of info message'
    print_question 'Example of prompt message'
  fi
  sleep 2 'Example of waiting message'
}

# All of your code should be put here
main() {
  demo__args "${@}"
  demo__prints
  return 0
}

# Get things started
sheli__main "${@}"

